trigger:
- main

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python39:
      python.version: '3.9'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install .[test]
  displayName: 'Install dependencies'

- script: |
    black --check src/ tests/
    isort --profile black -c src/ tests/
  displayName: "Formatting check"

- script: |
    pytest -v tests/
  displayName: 'Unit tests'

# - script: |
#     pip install build
#     pip install twine
#   displayName: 'Install build and twine'

# - script: |
#     python -m build -w
#   displayName: 'Python build'

# - task: TwineAuthenticate@1
#   inputs:
#     artifactFeed: ebadkamil/nexi-feed
#   displayName: 'Twine Authenticate'

# - script: |
#     python -m twine upload -r nexi-feed --config-file $(PYPIRC_PATH) dist/*.whl
#   displayName: 'Upload to feed'