trigger:
- main

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python39:
      python.version: '3.9'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install .[test]
  displayName: 'Install dependencies'

- script: |
    black --check src/ tests/
    isort --profile black -c src/ tests/
  displayName: "Formatting check"

- script: |
    pytest -v tests/
  displayName: 'Unit tests'
